### PR TITLE
Fix pickling/unpickling of Resource objects

### PR DESCRIPTION
**Pull request by evansloan**
Add \_\_getstate\_\_ and \_\_setstate\_\_ methods to the Resource class to avoid hitting the recursion limit when trying to pickle/unpickle Resource objects.

A similar issue/solution can be found [here](https://stackoverflow.com/a/12102691)

### CODE REVIEW

**Comment by rhgrant10** [comment]
Thanks for this! I'll take a look and hopefully get it merged soon. Sorry for the delay.

**Comment by rhgrant10** [comment]
Huh. TIL. This is quite interesting. I've not really had occasion to pickle/unpickle things before. Thanks, LGTM.

**Comment by rhgrant10** [comment]
Available in 0.10.0 on PyPI :)

**Comment by evansloan** [comment]
Awesome! Thank you

**Pull request merged**
