### PR TITLE
Adding support for Gallery endpoint 

### PR DESCRIPTION
**Pull request by pmcgannon22**
The Gallery is a relatively recent addition (~12-18 months ago) to GroupMe. It is useful to find media from the group quickly. 

The Gallery endpoint is not officially supported within their API docs, but adding support within the library won't regress any other functionality and is a useful addition. 

In addition, I added the ability to get a single group by ID. I know this is possible to do with the FilterList, but that still requires a call that returns the entire list of groups, rather than just one. This is a common task and a more efficient method for it seems useful.

### CODE REVIEW

**Comment by rhgrant10** [comment]
Wow! Firstly, thank you for the work you put into this. I've only glanced at it (I'm mobile) but it looks great. I'll take a closer look at it, hopefully tonight. This would definitely precipitate a release.

**Comment by pmcgannon22** [comment]
Great to hear! 

When you take a look at it, I would make sure everything is working fine when you test it with the paging in your own groups, since it uses an RFC 3339 timestamp rather than a before_id style of paging. In order to maintain compatibility with the Message class, I convert the message created timestamp. I am pretty sure it is all good, but it would be nice to get another pair of eyes besides my own looking out for any

**Comment by rhgrant10** [comment]
So I've been playing around with it. I think there are some issues with respect to the ordering, as you suggested. Here's the test file I cobbled together (although unit tests for this would be fantastic, I think we're still sorting out what the API actually returns here):

```python
import sys

import groupy


THRESHOLD = 200

# Sort the groups with more than THRESHOLD messages.
groups = groupy.Group.list()
groups = list(filter(lambda x: x.message_count > THRESHOLD, groups))
groups.sort(key=lambda x: x.message_count)

# Out of the groups with more than THRESHOLD messages, find the group
# that has the least number of messages and more than THRESHOLD gallery
# entries.
group = None
for g in groups:
    newest_pics = g.gallery()
    print('\n{0}'.format(g))
    print('Getting pics.', end='', flush=True)
    all_pics = g.gallery()
    while all_pics.iolder():
        print('.', end='', flush=True)
    print(len(all_pics))
    if len(all_pics) > THRESHOLD:
        group = g
        print('Group chosen: {0}'.format(group))
        break

if group is None:
    print('Sorry, you must have a group with at least {threshold} messages '
          'and {threshold} gallery entries'.format(threshold=THRESHOLD))
    sys.exit(2)

# Get all messages
newest_messages = group.messages()
print('Getting messages.', end='', flush=True)
all_messages = group.messages()
while all_messages.iolder():
    print('.', end='', flush=True)
print(len(all_messages))

# Get the pertinent message pages
# (oldest, newer) and (older, newest)
older_messages = newest_messages.older()
oldest_messages = group.messages(after=0)
newer_messages = oldest_messages.newer()

# Get (oldest, newer) as ioldest and (older, newest) as inewest
inewest_messages = group.messages()
inewest_messages.iolder()
ioldest_messages = group.messages(after=0)
ioldest_messages.inewer()

# Make sure we have enough messages to assert our suspected truths
assert len(all_messages) > len(newest_messages) + len(older_messages)
assert len(all_messages) > len(newer_messages) + len(oldest_messages)

# Get the pertinent gallery pages
# (oldest, newer) and (older, newest)
older_pics = newest_pics.older()
oldest_pics = group.gallery(after=0)
newer_pics = oldest_pics.newer()

# Get (oldest, newer) as ioldest and (older, newest) as inewest
inewest_pics = group.gallery()
inewest_pics.iolder()
ioldest_pics = group.gallery(after=0)
ioldest_pics.inewer()

# Make sure we have enough gallery entries to assert our suspected truths
assert len(all_pics) > len(newest_pics) + len(older_pics)
assert len(all_pics) > len(newer_pics) + len(oldest_pics)

# Messages
assert older_messages.oldest.created_at < older_messages.newest.created_at
assert newest_messages.oldest.created_at < newest_messages.newest.created_at
assert older_messages.newest.created_at < newest_messages.oldest.created_at
assert newest_messages.first == newest_messages.newest
assert older_messages.first == older_messages.newest
assert newest_messages.last == newest_messages.oldest
assert older_messages.last == older_messages.oldest

# Gallery
assert older_pics.oldest.created_at < older_pics.newest.created_at
assert newest_pics.oldest.created_at < newest_pics.newest.created_at
assert older_pics.newest.created_at < newest_pics.oldest.created_at
assert newest_pics.first == newest_pics.newest
assert older_pics.first == older_pics.newest
assert newest_pics.last == newest_pics.oldest
assert older_pics.last == older_pics.oldest

# Messages, backward
assert oldest_messages.oldest.created_at < oldest_messages.newest.created_at
assert newer_messages.oldest.created_at < newer_messages.newest.created_at
assert oldest_messages.newest.created_at < newer_messages.oldest.created_at
assert oldest_messages.last == oldest_messages.newest
assert newer_messages.last == newer_messages.newest
assert oldest_messages.first == oldest_messages.oldest
assert newer_messages.first == newer_messages.oldest

# Gallery, backward
assert oldest_pics.oldest.created_at < oldest_pics.newest.created_at
# assert newer_pics.oldest.created_at < newer_pics.newest.created_at
# assert oldest_pics.newest.created_at < newer_pics.oldest.created_at
# assert oldest_pics.last == oldest_pics.newest
# assert newer_pics.last == newer_pics.newest
# assert oldest_pics.first == oldest_pics.oldest
# assert newer_pics.first == newer_pics.oldest

# Test i* functionality
assert ioldest_messages.oldest.created_at < ioldest_messages.newest.created_at
assert inewest_messages.oldest.created_at < inewest_messages.newest.created_at
assert ioldest_pics.oldest.created_at < ioldest_pics.newest.created_at
assert inewest_pics.oldest.created_at < inewest_pics.newest.created_at
```

Essentially, it tests newer/older and inewer/iolder functionality for both group messages and group gallery. The lines that are commented currently fail.

I played around with the code a bit, and although I see some things that I knew were incorrect, fixing them didn't make *all* of the above asserts pass. The diff was:

```diff
diff --git a/groupy/object/listers.py b/groupy/object/listers.py
index 4833c5a..db62b9c 100644
--- a/groupy/object/listers.py
+++ b/groupy/object/listers.py
@@ -192,7 +192,7 @@ class GalleryPager(MessagePager):
         :returns: a newer page of messages
         :rtype: :class:`~groupy.object.listers.MessagePager`
         """
-        return self.group.gallery(after=datetime.utcfromtimestamp(int(self.oldest.created_at.timestamp())))
+        return self.group.gallery(after=datetime.utcfromtimestamp(int(self.newest.created_at.timestamp())))

     def older(self):
         """Return the previous (older) page of messages.
diff --git a/groupy/object/responses.py b/groupy/object/responses.py
index a22c69c..f265d14 100644
--- a/groupy/object/responses.py
diff --git a/groupy/object/listers.py b/groupy/object/listers.py
index 4833c5a..db62b9c 100644
--- a/groupy/object/listers.py
+++ b/groupy/object/listers.py
@@ -192,7 +192,7 @@ class GalleryPager(MessagePager):
         :returns: a newer page of messages
         :rtype: :class:`~groupy.object.listers.MessagePager`
         """
-        return self.group.gallery(after=datetime.utcfromtimestamp(int(self.oldest.created_at.timestamp())))
+        return self.group.gallery(after=datetime.utcfromtimestamp(int(self.newest.created_at.timestamp())))

     def older(self):
         """Return the previous (older) page of messages.
diff --git a/groupy/object/responses.py b/groupy/object/responses.py
index a22c69c..f265d14 100644
--- a/groupy/object/responses.py
+++ b/groupy/object/responses.py
@@ -169,7 +169,7 @@ class Recipient(ApiResponse):

         # Fetch the messages.
         try:
-            r = endpoint.Gallery.index(self._idkey, before=before,
+            r = endpoint.Gallery.index(self._idkey, before=before,
                                         since=since, after=after, limit=limit)
         except errors.ApiError as e:
             # NOT_MODIFIED, in this case, means no more messages. Some versions
@@ -185,7 +185,7 @@ class Recipient(ApiResponse):
             raise e

         gallery_messages = (Message(self, **m) for m in r[self._mkey])
-        return GalleryPager(self, gallery_messages)
+        return GalleryPager(self, gallery_messages, backward=backward)


 class Group(Recipient):
@@ -778,4 +778,4 @@ class User(ApiResponse):
             if e.args[0]['code'] != status.OK:
                 raise
             return e.args[0]['code']
-        return True
\ No newline at end of file
+        return True
```

A couple of those lines differ only in whitespace but the rest are pretty important. Perhaps you can use all this to help me sort out why all of the asserts won't pass!

Also, sorry for the delay; I managed to get bronchitis (all better now).

**Comment by rhgrant10** [comment]
fwiw I'm in the process of refactoring to address a number of long running concerns. Even though we couldn't get to the cause of the ordering issue, you basically made me aware of an entire undocumented endpoint so I'm going to merge this in anyway. That way you're listed as a contributor :)

I'll be sure to include gallery support in the next release!

**Pull request merged**
